### ISSUE TITLE
Didn't effect the "Divi Builder Setting"

### ISSUE THREAD

**Issue by danidee** [jonathanbossenger/divi-full-screen-page-builder-modules#1]
builder setting modal still shows the same dimension.

**Comment by jonathanbossenger** [comment]
Thanks

Could you please confirm the steps to reproduce this error (it just makes it easier for when I eventually get round to fixing it)

**Comment by danidee** [comment]
not sure how to add an image here, but it's the one to edit the page css. 

Anyway I got around and tweaked it a bit to get the result.

`add_action('admin_head', 'full_screen_page_builder');
function full_screen_page_builder() {
    echo '<style>
        .et_pb_modal_settings_container {
        width: 95% !important;
        padding: 0 !important;
        margin: 0 !important;
        left:2.5% !important;
        height: 95% !important;
        top: 35px;
    }
    .et_pb_prompt_modal{
    top:50% !important;
    width:95%;
    height:90%;
    left:18% !important;
}
    .et-pb-options-tabs-links {
        width: 100% !important;
    }
  </style>';
}`
