### ISSUE TITLE
Problem adding item to library

### ISSUE THREAD

**Issue by philsimon** [jonathanbossenger/divi-full-screen-page-builder-modules#2]
Trying to add an item to the library shows this:

`http://screencast.com/t/tcJ8Od24J7`

Anyone else have this issue? Chrome, Mac.

**Comment by jonathanbossenger** [comment]
Thanks Phil, Michlle Nunan had a similar issue. Will look into it when I have a moment.

**Comment by jonathanbossenger** [comment]
@philsimon I have merged a fix for this, please let me know if it works. #4

**Comment by philsimon** [comment]
Thanks. It seems to work!

On Mon, Jul 11, 2016 at 4:14 AM, jonathanbossenger <notifications@github.com

> wrote:
> 
> @philsimon https://github.com/philsimon I have merged a fix for this,
> please let me know if it works. #4
> https://github.com/jonathanbossenger/divi-full-screen-page-builder-modules/pull/4
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/jonathanbossenger/divi-full-screen-page-builder-modules/issues/2#issuecomment-231706768,
> or mute the thread
> https://github.com/notifications/unsubscribe/AEgoDE3Unw-aQ0sQ2c4H-yxII4CIttnoks5qUiWegaJpZM4I_LOq
> .

## 

Regards,

Phil Simon
phil@philsimon.com
http://www.philsimon.com

*Read me: I abide by a three-email rule
http://www.philsimon.com/blog/favorites/new-rule-after-three-e-mails-we-talk/.
After three, we talk. *
