### ISSUE TITLE
Poor placement of Add to Library Modal

### ISSUE THREAD

**Issue by sassysasquatchstudios** [jonathanbossenger/divi-full-screen-page-builder-modules#3]
When I try to add a module to the library, the add to library modal is partially off the window and I can't access the settings for the save. 
![modalproblemdivifullscreen](https://cloud.githubusercontent.com/assets/350267/16716872/dae4ca84-46bd-11e6-9b19-202a495e9b7a.png)

**Comment by jonathanbossenger** [comment]
@halbrooktech I have merged a fix for this, please let me know if it works. #4
